name: 'IONOS-Deploy'
description: 'Deploy content to IONOS webspace'
inputs:
  service-host:
    description: 'The service endpoint to call in the action'
    required: true
  api-key:
    description: 'IONOS API Key'
    required: true
  project:
    description: 'IONOS project name'
    required: true
  dist-folder:
    description: 'Directory to deploy'
    required: true
    default: 'dist'
  remote-host:
    description: 'Remotehost to deploy'
    required: true
  branch-id:
    description: 'The IONOS.space branch id'
    required: true
  storage-quota:
    description: 'The allowed quota for the storage'
    required: true
  initial-build:
    description: 'is this the initial build of the branch'
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    API_KEY: ${{ inputs.api-key }}
    PROJECT: ${{ inputs.project }}
    SERVICE_HOST: ${{ inputs.service-host }}
    DIST_FOLDER: ${{ inputs.dist-folder }}
    REMOTE_HOST: ${{ inputs.remote-host }}
    BRANCH_ID: ${{ inputs.branch-id }}
    STORAGE_QUOTA: ${{ inputs.storage-quota }}
    INITIAL_BUILD: ${{ inputs.initial-build }}
