build:
  dist-folder: ./

deploy:
  force-bootstrap: false
  force-regular: false

  bootstrap:
    dump-database: #not for mvp
      source-branch: main
      schema: app-db

    copy-files: #not for mvp
      source-branch: main
      directories:
        - storage
        - other-dir

    build-excludes:
      - tests
      - node_modules

    remote-commands:
      - create SQL lite
      - php8.0 artisan migrate --force
      - php8.0 artisan cache:clear
      - php8.0 artisan config:clear
      - php8.0 artisan route:clear
      - php8.0 artisan view:clear
      - php8.0 artisan config:cache
      - php8.0 artisan route:cache
      - php8.0 artisan view:cache
      - seed DB

  regular:
    build-excludes:
      - tests
      - node_modules
      - storage

    run-excludes: #not for mvp
      - dir-on-space

    remote-commands:
      - php8.0 artisan migrate --force
      - php8.0 artisan cache:clear
      - php8.0 artisan config:clear
      - php8.0 artisan route:clear
      - php8.0 artisan view:clear
      - php8.0 artisan config:cache
      - php8.0 artisan route:cache
      - php8.0 artisan view:cache
